# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 08:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_good', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('ts_document', models.TextField(blank=True, help_text='The content that will be searched over', null=True)),
                ('ts_document_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='The ts_vector for the document field', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('source_name', models.CharField(max_length=255, verbose_name='source_name')),
                ('destination', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination_name', models.CharField(max_length=255, verbose_name='destination_name')),
                ('status', models.CharField(choices=[('ACCEPTED', 'accepted'), ('PENDING_APPROAVAL', 'pending_approval'), ('CANCELLED', 'cancelled')], max_length=50)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courier_delivery_goods', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_delivery_goods', to=settings.AUTH_USER_MODEL)),
                ('delivery_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_good_delivery_orders', to='delivery_good.DeliveryGood')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
    ]
