# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('PENDING', 'pending'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=50),
        ),
    ]
