# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 19:22
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ts_document', models.TextField(blank=True, help_text='The content that will be searched over', null=True)),
                ('ts_document_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='The ts_vector for the document field', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('COURIER', 'Courier')], max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'ordering': ('-updated', '-created'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('ts_document', models.TextField(blank=True, help_text='The content that will be searched over', null=True)),
                ('ts_document_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='The ts_vector for the document field', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='user_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to='user.User')),
            ],
            options={
                'abstract': False,
                'ordering': ('-updated', '-created'),
            },
        ),
    ]
