---
- hosts: bina-bikers
  name: Bina bikers app server
  vars:
    bina_bikers_version: "0.0.3a1054+g1b14388"
    debug: "false"
    gunicorn_timeout: 60
    gunicorn_graceful_timeout: 1
    setup_search: false
    load_icd10_data: true
    deploy_user: "bina_bikers"
    deploy_group: "bina_bikers"
    use_localhost_postgresql: false
  roles:
      - supervisor
      - nginx
      - python
      - ssh
      - {
          role: "bina_bikers",
          server_name: "104.236.52.240:8080",
          allowed_hosts: ".localhost,104.236.52.240",
          name: "bina_bikers",
          nginx_port: "8080",
          ssl_on: false,
          database_url: "postgres://bina_bikers:bina_bikers@104.236.52.240:5432/bina_bikers",
        }
      - {
          role: postgresql,
          pg_version: '9.6'
        }
  tags: ["bina-bikers"]
